### ISSUE TITLE
Implement Cache

### ISSUE THREAD

**Issue by lucastliu** [lucastliu/gmailfs#15]
Implement a cache systCache most recently read (requested) emails

Cache (pre-fetch) the new emails

Keep the most recent 100 emails based on these 2 policies

We define “most recent” as:
For new emails: receive time
For old emails that are read:  most recent user access time
Current plan: remove the cached emails on start up
Optional: After the program ends, cached email will remain and next time we will only update the new coming emails from the last execution.

**Comment by woooks** [comment]
Implement fetch_new_message(message_id) and delete_message(message_id)
